service: text-moderation-api-ts

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  memorySize: 512
  timeout: 15
  apiGateway:
    apiKeys:
      - TextModerationApiKey
    usagePlan:
      quota:
        limit: 1000000
        period: MONTH
      throttle:
        burstLimit: 2000
        rateLimit: 1000

functions:
  moderate:
    handler: handler.lambdaHandler
    events:
      - http:
          path: moderate
          method: post
          private: true # API key required for access

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    region: eu-central-1
    host: 0.0.0.0
    stage:
